name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Remove folder and clone repository
        run: |
          rm -rf QuickTask
          git clone https://github.com/Kevin-Illu/QuickTask.git QuickTask
        working-directory: $HOME
      - name: Configure Git
        run: |
          git config --global --add safe.directory $HOME/QuickTask
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run make

