name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Configure Git
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            git config --global --add safe.directory $HOME/QuickTask
          else
            git config --global --add safe.directory "$HOME\QuickTask"
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run make

