name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifacts
          path: |
            out/QuickTask-*

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/QuickTask-*
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release of version ${{ env.npm_package_version }}
          draft: false
          prerelease: false

